<style>
p {
  text-align: justify;  
  text-indent: 20px;   
}
</style>  

# Introdução    
***  


<p>Segundo o CONTRAN na resolução 311/09 acerca da obrigatoriedade do equipamento suplementar de segurança Airbag na frota total de veículos, assim como a 380/11 que visa estabelecer o mesmo critério de implementação acerca do ABS, determina que até o ano de 2014 todos veículos novos (que tenham ao menos quatro rodas) produzidos nacionalmente ou importados devem possuir tais equipamentos de segurança.  

<p>Pautando-se no período de início da implementação até à frota total de veículos da categoria mencionada, os dados de sinistros em análise e suas especificidades foram extraídos da Base de Dados da PRF (Polícia Rodoviária Federal) e selecionados os anos de 2007 e 2008 para o estudo do período que antecede à obrigatoriedade, e 2014 à 2023 (selecionando apenas veículos com ano de fabricação superior a 2014) para análise da efetividade de ambos equipamentos de segurança após a implementação total em 2014. Dados pertencentes aos anos anteriores aos que foram estabelecidos como período inicial não foram utilizados pelas inconsistências nos registros feitos pela PRF.  

<p>O objetivo deste documento é avaliar o impacto da obrigatoriedade do Airbag e ABS na severidade dos sinistros de trânsito. A pesquisa utilizou dados de sinistros nas rodovias federais brasileiras disponibilizados pela da Polícia Rodoviária Federal. 

## Estudos sobre o impacto de Airbags

<p>Um estudo baseado meta-análise realizado por Høye (2010) avaliou em diversos países os efeitos dos Airbags frontais nas mortes de condutores com e sem cinto de segurança, as variáveis incluíam veículos de diferentes portes e variados tipos de Airbags. Os resultados indicaram uma redução de 22% nas mortes nos sinistros em geral e uma redução de 18% para as colisões frontais com o uso de Airbag associado ao cinto de segurança. No entanto, não foi observada qualquer redução global da mortalidade entre os condutores sem cinto de segurança e, em alguns casos, o risco de mortalidade aumentou, especialmente em sinistros sem colisão enfatizando assim, a importância do controle das variáveis observadas, como o uso do cinto de segurança e a direção do impacto do veículo para avaliar com maior precisão eficácia dos Airbags como item de segurança veicular.  

<p>Digges (2024) fez uma retrospectiva histórica acerca da introdução de Airbags frontais nas frotas em veículos nos Estados Unidos a partir do final da década de 60. Nesse estudo observou que os métodos empregados na introdução de Airbags frontais em veículos incluíram contratos de pesquisa avançada com grandes montadoras para construção e testes de Veículos Experimentais de Segurança, com os quais eram avaliados diversos modelos de Airbags para os ocupantes dos bancos dianteiros dos veículos, permitindo assim um gradual melhoramento nas tecnologias de segurança dos mesmos, além de serem avaliados modelos de Airbags para veículos específicos, conduzindo simulações de computador, testes de trenó e testes de colisão com barreiras para avaliar o desempenho de proteção para os ocupantes fora de posição.  Apesar dos atrasos regulatórios iniciais e da oposição da indústria e controversas de interesses de fornecedores e políticos, as intervenções de figuras influentes e a evolução da conscientização sobre segurança levaram à exigência de Airbags em todos os carros e caminhões leves até 1º de setembro de 1998.  

<p>Samantray e Parashar (2021) realizaram o estudo na Índia fornecendo uma visão abrangente da eficácia do Airbags em automóveis. No trabalho é discutido a evolução desse sistema de segurança, desde projetos iniciais até os mais avançados, destacando a importância do desenvolvimento contínuo de pesquisas acerca de materiais com alta resistência que garantem maior segurança aos ocupantes do veículo. Testes com bonecos foram realizados para avaliar também a eficácia de  outros tipos de Airbags como os de cortina centrais frontais e laterais torácicos. Os autores enfatizam a importância de se projetar e implementar de forma adequada os sistemas de Airbags para reduzir lesões, minimizando a força exercida sobre os passageiros durante as colisões.

<p>Viano (2024) detalhou um histórico de evolução dos benefícios e riscos de segurança dos Airbags com foco na análise de dados de campo sobre mortes de Airbags e estudos sobre mecanismos de lesão por disparo. A pesquisa realizada nos Estados Unidos inclui comparações da NCAP de dados mais antigos aos mais recentes assim como diferentes configurações de retenção em cenários de colisão, como os testes de trenó e de colisão frontal da NHTSA com e sem cinto de segurança e Airbags. O estudo demonstrou que os Airbags, especialmente quando utilizados em conjunto com cintos de segurança, são eficazes na prevenção de mortes e ferimentos em colisões. Segundo Viano (2024) a diminuição foi 80,5% menor em motoristas e 82,0%, em passageiros com cintos e Airbags em testes de colisão NCAP a 35 mph de veículos MY 2012–20. E em geral a redução do risco foi de 69,7% com uso de cinto e Airbags acionados em 96,1% dos acidentes. Por fim, observou-se também riscos associados ao acionamento e ruptura de Airbags, incluindo casos de lesões e mortes relacionadas a isso, levando a necessidade de avanços no design do mesmo para mitigação de tais riscos.

<p>O estudo de Dzinyela et al., 2024 buscou identificar fatores acerca da gravidade das lesões de motoristas com e sem Airbags acionados em colisões de veículos únicos em rodovias do estado do Alabama nos anos de 2016 a 2018. Foram utilizados modelos estatísticos avançados que identificaram uma heterogeneidade nas médias e variâncias dos parâmetros aleatórios levando em conta a heterogeneidade não observada na determinação dos fatores que afetam a gravidade das lesões dos motoristas de acordo com os acionamentos dos Airbags. A análise revelou mudanças significativas nos efeitos das variáveis ao longo do tempo, levando à estimação de modelos específicos para cada ano e para acidentes com Airbags acionados ou não, apontando também que fatores como o tipo de veículo,  localização e colisões com objetos específicos têm um impacto consistente na gravidade das lesões, realçando a importância de concentrar os esforços de melhoria da segurança nestas variáveis, ressaltando  a complexidade dos acidentes rodoviários e os desafios na documentação de todos os fatores que os influenciam, enfatizando a necessidade de abordagens estatísticas avançadas para melhorar as inferências na análise de dados dos acidentes.  

<p>Com o objetivo de investigar a gravidade das lesões causadas na cabeça dos ocupantes durante impactos frontais e também otimizar os parâmetros estruturais veiculares para aumentar a segurança dos mesmos, aderindo ao regulamento da União Européia ECE R9, Asadinia et al., 2018 utilizou em seu estudo os métodos Taguchi e Análise de Variância (ANOVA) para analisar os efeitos de diferentes parâmetros nas métricas de segurança dos ocupantes, especificamente a aceleração máxima da cabeça. Os autores utilizaram o software Pam Crash e criam uma série de experimentos baseados nas matrizes ortogonais de Taguchi, que permitiram testes eficientes de múltiplos fatores com um número reduzido de experimentos, identificando, assim, os parâmetros mais significativos que afetam a segurança dos ocupantes. Os resultados indicam que os vários testes atenderam aos requisitos da ECE R94, demonstrando que o processo de otimização aumenta efetivamente a segurança dos ocupantes. O estudo destacou a importância de parâmetros específicos, como a distância de acionamento do Airbag e a integridade estrutural veicular, na redução do risco de lesões durante colisões.  

<p> Utilizando simulações e comparações de testes de colisões veiculares para analisar os efeitos do atraso no acionamento dos Airbags através do software PC Crash, Radu et al., 2018 simulou a cinemática dos ocupantes com foco nos valores de aceleração da cabeça em tempos variados de acionamento do Airbag (0 ms, 40 ms, 80-100 ms) assim como a comparação desses cenários para entender como os atrasos afetam a aceleração da cabeça e potenciais lesões. Foi também considerando o papel dos sistemas de pré-tensão dos cintos de segurança em conjunto com o acionamento do Airbag, porém observou-se um impacto mínimo na gravidade das mesmas. Os resultados revelam que atrasos no acionamento do Airbag podem aumentar a aceleração da cabeça em até 46%, o que se correlaciona com uma maior probabilidade de lesões e que, um atraso específico de 100 ms pode levar a um aumento de 54%, sugerindo que o Airbag, neste caso, pode passar de um dispositivo de proteção a uma fonte potencial de lesões, ressaltando a necessidade de um tempo preciso de acionamento do Airbag para aumentar a segurança dos ocupantes em colisões de veículos.  

<p>Ahmad et al., 2017 comparou os resultados de lesões nos ocupantes de veículos com e sem Airbags frontais usando manequins adultos em um cenário de teste de colisão frontal onde os veículos foram impelidos contra uma barreira estacionária a uma velocidade de 64 km/h para avaliar a eficácia do equipamento de segurança em estudo. Os dados de lesões nas extremidades superiores e na cabeça, foram coletados e analisados usando o Critério de Lesão na Cabeça (HIC) e o 3ms e foram calculados com base em medições de aceleração durante o pulso de colisão. Os resultados revelaram que as métricas de lesões na cabeça do condutor melhoraram 87% quando o Airbag estava presente e que o pico de aceleração 3ms que quantifica as medidas de impacto na região do tórax foi reduzida em 66%, diminuindo assim potenciais lesões. Para os passageiros dianteiros, os valores de aceleração HIC e 3ms foram reduzidos em 48% e 21%, respectivamente, ao comparar o veículo com e sem Airbag.  

<p>Padmanaban e Eyges (2009) avaliaram a eficácia dos Airbags de segunda geração (de 1998 ou posterior) na redução das mortes de condutores em colisões frontais graves, utilizando dados de sinistros fatais nos EUA entre 1998 e 2007. Os pesquisadores extraíram as informações do Fatality Analysis Reporting System (FARS) e do National Automotive Sampling System/Crashworthiness Data System (NASS/CDS) e fizeram uma análise de dados combinados entre veículos envolvidos em uma mesma colisão, usando como critério de seleção que, ao menos, um dos veículos tivesse o ano de fabricação acima de 1998, assim como um deles houvesse fatalidade apesar do uso de cinto de segurança. Os resultados indicaram que o acionamento do Airbag não foi um preditor estatisticamente significativo de fatalidade do motorista em colisões frontais de alta gravidade, mas a razão de massa veicular aumentada em 10% gera 54% mais chances de fatalidade, acréscimo de 10 anos na idade do condutor aumenta 52% e consumo de álcool 110%, concluindo que, embora os Airbags sejam um importante recurso de segurança, a sua eficácia na prevenção de mortes em acidentes graves pode ser limitada em comparação a outros fatores.  

<p>Usando os bancos de dados, como PubMed, Scopus e HealLink para análise dos perigos decorrentes do uso inadequado de Airbags entre 1993 e 2000 nos EUA. Itans e Stergiannis (2011) observaram que os Airbags podem reduzir a incidência de fatalidades em colisões frontais veiculares em aproximadamente 25% quando comparados à cenários onde apenas os cintos de segurança são usados, além de reduzir as lesões dos passageiros em até 50%. No entanto, os autores salientaram que o uso ou acionamento inadequado do mesmo pode causar lesões graves, incluindo queimaduras diversas pela liberação de gases, lesões oculares 2,5%, lesões e fraturas em extremidades superiores 2,7% e 4,4%, respectivamente.  

<p>Realizando uma revisão na literatura acerca da história, materiais utilizados, princípios de funcionamento, tipos e escopo futuro dos Airbags em veículos, Bhasin (2020) forneceu uma visão abrangente da evolução das tecnologias de Airbags desde os primeiros designs até os sistemas atuais, enfatizando a eficácia e a confiabilidade  dos mesmos na redução de mortes de motoristas em colisões frontais citando sobre os materiais comumente usados em Airbags, como náilon e poliéster, e explicou o funcionamento desses sistemas, que envolvem sensores, módulos de controle e propelentes químicos para inflar os Airbags rapidamente ao detectar condições específicas. Além disso, mencionou vários tipos de Airbags, como frontais, laterais e de cortina, cada um com diferentes funções de segurança mencionando que futuramente esses sistemas deverão ser mais econômicos, leves e integrados com sensores inteligentes para medidas de segurança aprimoradas em automóveis aumentando a  eficácia dos Airbags como um componente vital da engenharia de segurança automotiva.  

<p>Através da coleta de informações de sinistros no banco de dados da Swedish Transport Administration, Strandroth (2015) fez a análise dos dados que continham fatalidades de passageiros na Suécia entre 2000 e 2010, centrando-se no desenvolvimento e validação de um método preditivo para avaliar a eficácia das intervenções de segurança rodoviária implementadas até 2010 usou também fontes externas como o Serviço Meteorológico Sueco e O Instituto Hidrológico para levar em conta fatores ambientais que afetam os resultados dos acidentes além de outros fatores contribuintes como velocidade, fluxo de tráfego e comportamento do motorista. Ao comparar os resultados estimados com os resultados reais, o autor descobriu uma redução prevista de mortes de 41% entre 2000 e 2010, porém a redução real observada foi de 53%, mostrando assim, a eficácia das intervenções de segurança rodoviária implementadas durante esse período.  

## Estudos sobre o impacto de ABS  

<p>Nos Estados Unidos, Bhalla e Gleason (2020) desenvolveram um estudo com o objetivo de avaliar o impacto da implementação de tecnologias de segurança veicular na América Latina e no Caribe para reduzir mortes e lesões no trânsito. A metodologia envolveu o uso de dados sobre mortalidade e sinistros de vários países da região e a estimativa dos benefícios da difusão das tecnologias de segurança veicular em termos da redução da mortalidade e do indicador DALYs (Disability-Adjusted Life Years). Especificamente, o uso do controle eletrônico de estabilidade juntamente com os freios ABS poderia resultar em 19,40% menos mortes e um indicador DALYs 17% menor. Já o uso dos Airbags mostraram que, embora eles tenham benefícios em termos de melhoria da segurança do veículo, os seus efeitos não foram tão substanciais como o citado anteriormente. 

<p>Voltado para o estudo de tecnologias na área de mecância, Jitesh (2014)  em sua revisão de literatura destacou a importância do ABS em veículos modernos para evitar deslizamento das rodas e travamento após a aplicação do freio, associando o funcionamento do ABS aos sensores de velocidade das rodas para detectar alterações na densidade do fluxo magnético, convertendo-as em sinais elétricos que são  enviados ao módulo de controle para regulação adequada da pressão do freio, enfatizando o papel crítico do desempenho dos pneus em veículos equipados com ABS, onde a manutenção de um equilíbrio entre as forças de tração dos pneus e a taxa de deslizamento é crucial para evitar o travamento das rodas. A pesquisa destaca os avanços nas tecnologias da área, permitindo que os motoristas tenham melhor controle em condições desafiadoras de estrada evitando possíveis acidentes.

<p>Com o objetivo comparar as taxas anuais de sinistros (RTCs) em carros  equipados com e sem Sistema de Frenagem Antibloqueio (ABS) de um mesmo fabricante de veículos no Irã, (Khorasani-Zavareh et al., 2013) coletou os dados estudados através de uma pesquisa telefônica estruturada para obter informações sobre o número de sinistros, perdas financeiras e percepções dos motoristas em relação ao ABS. A amostra foi composta por 1.232 condutores de veículos equipados com ABS e 3.123 sem ABS, selecionados por meio de amostragem aleatória simples do cadastro da Organização Central de Seguros. Entre os motoristas de veículos equipados com ABS, 61,1% relataram situações em que acreditavam que o sistema havia evitado uma colisão e 44,1% dos motoristas com ABS não sabiam como usar o ABS de forma eficaz. O estudo descobriu também que a incidência de RTCs devido a falha de freio foi maior no grupo sem ABS, com uma taxa de 50,3 RTCs por 1.000 veículos/ano em comparação com 30,0 RTCs por 1.000 veículos/ano para os com ABS.  

<p>O estudo feito na Índia por Subhash e Deivanthan (2017) aplicou a modelagem e simulação de Sistemas de Frenagem Antibloqueio (ABS) em veículos utilizando os softwares Matlab e CARSIM. Vários métodos de controle, como lógica difusa e controle de sistema cinza, são explorados para desenvolver inicialmente modelos ABS para rodas individuais, com foco na previsão precisa do deslizamento das rodas e na manutenção do controle durante a frenagem. O estudo enfatiza a necessidade de passar de modelos de roda única para simulações completas de veículos para obter resultados mais precisos. Os resultados dos modelos ABS desenvolvidos para veículos do segmento hatchback e van mostram variações significativas na pressão do cilindro da roda, ângulo de direção, taxas de escorregamento e velocidades das rodas durante processos de curvas acentuadas, destacando a importância da modelagem ABS abrangente para uma distribuição eficaz da pressão de freio e estabilidade do veículo.  

<p>A pesquisa realizada na Índia por Khachane e Shrivastav (2016) discutiu acerca do Sistema de Frenagem Antibloqueio (ABS) e seu avanço através da distribuição eletrônica da força de frenagem (EBD) na indústria automobilística. O ABS aumenta a segurança reduzindo a distância de frenagem, aumentando a eficiência dos pneus e mantendo a estabilidade do veículo. No entanto, o ABS pode não funcionar eficazmente em condições de estrada adversas. O EBD resolve esta limitação distribuindo eficientemente a força de travagem mesmo em estradas geladas ou molhadas, melhorando a estabilidade e reduzindo a distância de travagem. Ao integrar unidades de controle eletrônico com motores e sensores mecânicos, a indústria está migrando para motores eletrônicos para fornecer recursos de segurança e conforto aprimorados aos clientes.  

<p>O estudo conduzido por Zulhilm et al., 2020 teve como objetivo analisar o efeito da frenagem de emergência sem Sistema de Frenagem Antibloqueio (ABS) no comportamento da dinâmica de veículos. O autor como modelo de veículo experimental um carro nacional da Malásia, o Proton Persona, que foi modificado com sensores e sistemas de aquisição de dados. Foram tomadas precauções de segurança, incluindo a utilização de uma pista de testes fechada e um motorista experiente. O estudo envolveu travagens de emergência a 60 km/h em estradas molhadas, com dados registados e analisados para fins de consistência. Os resultados indicaram que sem o ABS, o veículo enfrentava desafios na manutenção da estabilidade e da direção durante a travagem de emergência, destacando a importância do ABS na melhoria do desempenho da frenagem veicular e consequentemente da segurança rodoviária em geral.  

<p>Viramgama (2019) discutiu a importância dos Sistema ABS na prevenção do travamento e derrapagem das rodas durante a frenagem de emergência. O ABS consegue isso gerenciando taxas de escorregamento ideais para maximizar a força de atrito, reduzindo assim as distâncias de parada e melhorando a dirigibilidade. O autor destacou os princípios de frenagem de limite e frenagem de cadência utilizados pelos controladores ABS, juntamente com o papel crucial dos sensores de velocidade das rodas na funcionalidade do mesmo. Além disso, são explorados avanços na tecnologia do item em estudo, como Controle Automático de Tração (ATC) e Distribuição Eletrônica da Força de Frenagem (EBD). Estudos demonstraram que o ABS reduz o risco de múltiplas colisões de veículos, ao mesmo tempo que aumenta o risco de incidentes fora da estrada, enfatizando a eficácia e a importância do mesmo no aumento da segurança dos veículos.

